module.exports.nameList = [
  'Karen Mcintosh',
  'Scarlett Marshall',
  'Catrin Bender',
  'Erica Andrews',
  'Alivia Mcconnell',
  'Wilma Sanders',
  'Veronica Brady',
  'Roy Campbell',
  'Katy Macias',
  'Zachery Mcleod',
  'Youssef Barber',
  'Wanda Dickerson',
  'Kyle Delgado',
  'Shreya Payne',
  'Catherine Dale',
  'Fern Green',
  'Jemima Bray',
  'Jaya Rhodes',
  'Oscar Wolf',
  'Mariam Eaton',
  'Leena King',
  'Albie Watts',
  'Joel Cain',
  'Sabrina Carlson',
  'Jonah Hobbs',
  'Zohaib Arroyo',
  'Lydia Drake',
  'Corey Shannon',
  'Davina Meza',
  'Xavier Peck',
  'Riya Garner',
  'Tia Gould',
  'Sean Brown',
  'Richard Brooks',
  'Danielle Wyatt',
  'Alyssa Shaffer',
  'Sandra Chen',
  'Emilia Kim',
  'Lana Dyer',
  'Eleni Austin',
  'Lennon Hayes',
  'Abdirahman Mitchell',
  'Dewey Reid',
  'Calum Ryan',
  'Celia Doyle',
  'Finnley Hensley',
  'Owen Williams',
  'Daisie Blackwell',
  'Elisabeth Norton',
  'Mckenzie Lowe',
  'Allan Clark',
  'Alejandro Massey',
  'Azaan Coleman',
  'Dulcie Preston',
  'Bronwyn Murray',
  'Ela Sampson',
  'Gerald Jordan',
  'Kimberley Crawford',
  'Paula Hayden',
  'Minnie Wagner',
  'Benjamin Wade',
  'Isobel Thomas',
  'Anthony Pace',
  'Nora Grimes',
  'Stefan Landry',
  'Anisa Carrillo',
  'Alfie Torres',
  'Arianna Macdonald',
  'Seth Ortega',
  'Hollie Mcgrath',
  'Hamzah Callahan',
  'Maisie Farrell',
  'Hussein Bell',
  'Grover Leach',
  'Freddie Barker',
  'Barney Bird',
  'Esther Malone',
  'Axel Combs',
  'Autumn Bloggs',
  'Rosie Brewer',
  'Paul Todd',
  'Mario Osborn',
  'Eugene Lara',
  'Barbara Park',
  'Kaya Lucero',
  'Jamal Hammond',
  'Ana Bridges',
  'Fabian White',
  'Arnold Fernandez',
  'Freddy Lucas',
  'Raees Webb',
  'Marley Reeves',
  'Jackson Weiss',
  'Tamsin Levy',
  'Chelsea Quinn',
  'Subhan Acosta',
  'Leah John',
  'Kenneth Cobb',
  'Marianne Mcdaniel',
  'Kevin Mcguire',];

module.exports.locationList = [
  'City', 'Town', 'village', 'Hamlet', 'County', 'Borough', 'Township', 'Manor', 'Park', 'Estate'
];

module.exports.addressList = ['Astley Banks',
  'Chamberlain Holt',
  'Holmes Terrace',
  'Craig Pines',
  'Woodbury Knoll',
  'Crockwells Close',
  'Marcroft Avenue',
  'Chesham Link',
  'Spinney Dell',
  ' East Moor',
  ' Bottom O',
  ' Kirkland Lanes',
  ' Henley Bridge',
  ' Leyburn Ridge',
  ' Ripon Path',
  ' Swilletts Lane',
  ' Viking Down',
  ' Downham Loan',
  ' Reynolds Hollow',
  ' St Albans Ridings',
  ' Groove Street',
  ' Huddart Close',
  ' Hogarth Coppice',
  ' Fen Croft',
  ' Aberdeen Brambles',
  ' Herbert North',
  ' Wild Avenue',
  ' Harebell Oak',
  ' Sandhurst Lodge',
  ' Stevens Warren',
  ' Franklin Knoll',
  ' Walker Broadway',
  ' Gurlings Close',
  ' Holborn Ground',
  ' Cecil Hollow',
  ' Village Drive',
  ' Wallis Oval',
  ' Charnwood Fairway',
  ' Nusery Garden',
  ' Borough Oaks',
  ' Hillary Rise',
  ' Alice Passage',
  ' Holywell Downs',
  ' Frome Haven',
  ' Gas Mill',
  ' Seaforth Meadows',
  ' Montgomery Oak',
  ' Florence Esplanade',
  ' Tixall Road',
  ' West Ride',
  ' Harebell Nook',
  ' Keswick Place',
  ' Baldwin Brae',
  ' Barry Moor',
  ' Maple Square',
  ' Gold Hawthorns',
  ' Ashburnham Dell',
  ' Knoll Parc',
  ' Chartwell Glade',
  ' Frome Glebe',
  ' Humber Retreat',
  ' Hamilton Holt',
  ' Foxglove Furlong',
  ' Tamworth Valley',
  ' Clanfield Avenue',
  ' Oakhurst Brook',
  ' Clark Downs',
  ' Troon Oaks',
  ' Brompton Garden',
  ' Hunter Rise',
  ' Castleman Way',
  ' Priory Ridings',
  ' Harris Lea',
  ' Hood Hollies',
  ' Spencer Isaf',
  ' Berry Top',
  ' Stuart Common',
  ' Combe Courtyard',
  ' Brackley Pastures',
  ' Egerton Sidings',
  ' Woodview Circle',
  ' Brown Oval',
  ' Florence Pastures',
  ' Mallow Wharf',
  ' Kingfisher Down',
  ' Arnold Head',
  ' Hamilton Broadway',
];